# coding: utf-8

"""
    crush-main 平台接口（主平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetSuggestionExchangeListResponseInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'logo_url': 'str',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'logo_url': 'logoUrl',
        'name': 'name'
    }

    def __init__(self, id=None, logo_url=None, name=None):  # noqa: E501
        """GetSuggestionExchangeListResponseInner - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._logo_url = None
        self._name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if logo_url is not None:
            self.logo_url = logo_url
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this GetSuggestionExchangeListResponseInner.  # noqa: E501

        id  # noqa: E501

        :return: The id of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetSuggestionExchangeListResponseInner.

        id  # noqa: E501

        :param id: The id of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def logo_url(self):
        """Gets the logo_url of this GetSuggestionExchangeListResponseInner.  # noqa: E501

        logo地址  # noqa: E501

        :return: The logo_url of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._logo_url

    @logo_url.setter
    def logo_url(self, logo_url):
        """Sets the logo_url of this GetSuggestionExchangeListResponseInner.

        logo地址  # noqa: E501

        :param logo_url: The logo_url of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :type: str
        """

        self._logo_url = logo_url

    @property
    def name(self):
        """Gets the name of this GetSuggestionExchangeListResponseInner.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetSuggestionExchangeListResponseInner.

        名称  # noqa: E501

        :param name: The name of this GetSuggestionExchangeListResponseInner.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSuggestionExchangeListResponseInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSuggestionExchangeListResponseInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
