# coding: utf-8

"""
    crush 项目方平台（venture）相关接口

    crush 项目方相关的后段（staff）接口和（tenant）交易所接口  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.venture
from swagger_client.venture.models.application_detail_response import ApplicationDetailResponse  # noqa: E501
from swagger_client.venture.rest import ApiException


class TestApplicationDetailResponse:
    """ApplicationDetailResponse unit test stubs"""


    def testApplicationDetailResponse(self):
        """Test ApplicationDetailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.application_detail_response.ApplicationDetailResponse()  # noqa: E501
        pass


