# coding: utf-8

"""
    crush-staff 平台接口（职员管理平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetContactProjectsResponseItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'contact_at': 'datetime',
        'coin_logo_key': 'str',
        'coin_logo_url': 'str',
        'project_id': 'str',
        'full_name': 'str',
        'short_name': 'str',
        'issue_price': 'str',
        'issued_volume': 'str',
        'holders_number': 'str',
        'circulation_volume': 'str',
        'official_website': 'str',
        'block_browser': 'str'
    }

    attribute_map = {
        'id': 'id',
        'contact_at': 'contactAt',
        'coin_logo_key': 'coinLogoKey',
        'coin_logo_url': 'coinLogoUrl',
        'project_id': 'projectId',
        'full_name': 'fullName',
        'short_name': 'shortName',
        'issue_price': 'issuePrice',
        'issued_volume': 'issuedVolume',
        'holders_number': 'holdersNumber',
        'circulation_volume': 'circulationVolume',
        'official_website': 'officialWebsite',
        'block_browser': 'blockBrowser'
    }

    def __init__(self, id=None, contact_at=None, coin_logo_key=None, coin_logo_url=None, project_id=None, full_name=None, short_name=None, issue_price=None, issued_volume=None, holders_number=None, circulation_volume=None, official_website=None, block_browser=None):  # noqa: E501
        """GetContactProjectsResponseItems - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._contact_at = None
        self._coin_logo_key = None
        self._coin_logo_url = None
        self._project_id = None
        self._full_name = None
        self._short_name = None
        self._issue_price = None
        self._issued_volume = None
        self._holders_number = None
        self._circulation_volume = None
        self._official_website = None
        self._block_browser = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if contact_at is not None:
            self.contact_at = contact_at
        if coin_logo_key is not None:
            self.coin_logo_key = coin_logo_key
        if coin_logo_url is not None:
            self.coin_logo_url = coin_logo_url
        if project_id is not None:
            self.project_id = project_id
        if full_name is not None:
            self.full_name = full_name
        if short_name is not None:
            self.short_name = short_name
        if issue_price is not None:
            self.issue_price = issue_price
        if issued_volume is not None:
            self.issued_volume = issued_volume
        if holders_number is not None:
            self.holders_number = holders_number
        if circulation_volume is not None:
            self.circulation_volume = circulation_volume
        if official_website is not None:
            self.official_website = official_website
        if block_browser is not None:
            self.block_browser = block_browser

    @property
    def id(self):
        """Gets the id of this GetContactProjectsResponseItems.  # noqa: E501

        对接ID  # noqa: E501

        :return: The id of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetContactProjectsResponseItems.

        对接ID  # noqa: E501

        :param id: The id of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def contact_at(self):
        """Gets the contact_at of this GetContactProjectsResponseItems.  # noqa: E501

        接入时间  # noqa: E501

        :return: The contact_at of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: datetime
        """
        return self._contact_at

    @contact_at.setter
    def contact_at(self, contact_at):
        """Sets the contact_at of this GetContactProjectsResponseItems.

        接入时间  # noqa: E501

        :param contact_at: The contact_at of this GetContactProjectsResponseItems.  # noqa: E501
        :type: datetime
        """

        self._contact_at = contact_at

    @property
    def coin_logo_key(self):
        """Gets the coin_logo_key of this GetContactProjectsResponseItems.  # noqa: E501

        币种图标key  # noqa: E501

        :return: The coin_logo_key of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._coin_logo_key

    @coin_logo_key.setter
    def coin_logo_key(self, coin_logo_key):
        """Sets the coin_logo_key of this GetContactProjectsResponseItems.

        币种图标key  # noqa: E501

        :param coin_logo_key: The coin_logo_key of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._coin_logo_key = coin_logo_key

    @property
    def coin_logo_url(self):
        """Gets the coin_logo_url of this GetContactProjectsResponseItems.  # noqa: E501

        币种图标URL  # noqa: E501

        :return: The coin_logo_url of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._coin_logo_url

    @coin_logo_url.setter
    def coin_logo_url(self, coin_logo_url):
        """Sets the coin_logo_url of this GetContactProjectsResponseItems.

        币种图标URL  # noqa: E501

        :param coin_logo_url: The coin_logo_url of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._coin_logo_url = coin_logo_url

    @property
    def project_id(self):
        """Gets the project_id of this GetContactProjectsResponseItems.  # noqa: E501

        项目ID  # noqa: E501

        :return: The project_id of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this GetContactProjectsResponseItems.

        项目ID  # noqa: E501

        :param project_id: The project_id of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def full_name(self):
        """Gets the full_name of this GetContactProjectsResponseItems.  # noqa: E501

        币全称  # noqa: E501

        :return: The full_name of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this GetContactProjectsResponseItems.

        币全称  # noqa: E501

        :param full_name: The full_name of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def short_name(self):
        """Gets the short_name of this GetContactProjectsResponseItems.  # noqa: E501

        币简称  # noqa: E501

        :return: The short_name of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this GetContactProjectsResponseItems.

        币简称  # noqa: E501

        :param short_name: The short_name of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def issue_price(self):
        """Gets the issue_price of this GetContactProjectsResponseItems.  # noqa: E501

        发行价格  # noqa: E501

        :return: The issue_price of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._issue_price

    @issue_price.setter
    def issue_price(self, issue_price):
        """Sets the issue_price of this GetContactProjectsResponseItems.

        发行价格  # noqa: E501

        :param issue_price: The issue_price of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._issue_price = issue_price

    @property
    def issued_volume(self):
        """Gets the issued_volume of this GetContactProjectsResponseItems.  # noqa: E501

        发行量  # noqa: E501

        :return: The issued_volume of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._issued_volume

    @issued_volume.setter
    def issued_volume(self, issued_volume):
        """Sets the issued_volume of this GetContactProjectsResponseItems.

        发行量  # noqa: E501

        :param issued_volume: The issued_volume of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._issued_volume = issued_volume

    @property
    def holders_number(self):
        """Gets the holders_number of this GetContactProjectsResponseItems.  # noqa: E501

        持有人数  # noqa: E501

        :return: The holders_number of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._holders_number

    @holders_number.setter
    def holders_number(self, holders_number):
        """Sets the holders_number of this GetContactProjectsResponseItems.

        持有人数  # noqa: E501

        :param holders_number: The holders_number of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._holders_number = holders_number

    @property
    def circulation_volume(self):
        """Gets the circulation_volume of this GetContactProjectsResponseItems.  # noqa: E501

        流通数量  # noqa: E501

        :return: The circulation_volume of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._circulation_volume

    @circulation_volume.setter
    def circulation_volume(self, circulation_volume):
        """Sets the circulation_volume of this GetContactProjectsResponseItems.

        流通数量  # noqa: E501

        :param circulation_volume: The circulation_volume of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._circulation_volume = circulation_volume

    @property
    def official_website(self):
        """Gets the official_website of this GetContactProjectsResponseItems.  # noqa: E501

        官网  # noqa: E501

        :return: The official_website of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._official_website

    @official_website.setter
    def official_website(self, official_website):
        """Sets the official_website of this GetContactProjectsResponseItems.

        官网  # noqa: E501

        :param official_website: The official_website of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._official_website = official_website

    @property
    def block_browser(self):
        """Gets the block_browser of this GetContactProjectsResponseItems.  # noqa: E501

        区块浏览器  # noqa: E501

        :return: The block_browser of this GetContactProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._block_browser

    @block_browser.setter
    def block_browser(self, block_browser):
        """Sets the block_browser of this GetContactProjectsResponseItems.

        区块浏览器  # noqa: E501

        :param block_browser: The block_browser of this GetContactProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._block_browser = block_browser

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetContactProjectsResponseItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetContactProjectsResponseItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
