# coding: utf-8

"""
    crush-tenant 平台接口(租户平台)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PostMarketCloseRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'id': 'str',
        'closing_reason': 'str'
    }

    attribute_map = {
        'token': 'token',
        'id': 'id',
        'closing_reason': 'closingReason'
    }

    def __init__(self, token=None, id=None, closing_reason=None):  # noqa: E501
        """PostMarketCloseRequest - a model defined in Swagger"""  # noqa: E501

        self._token = None
        self._id = None
        self._closing_reason = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if id is not None:
            self.id = id
        if closing_reason is not None:
            self.closing_reason = closing_reason

    @property
    def token(self):
        """Gets the token of this PostMarketCloseRequest.  # noqa: E501

        token  # noqa: E501

        :return: The token of this PostMarketCloseRequest.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this PostMarketCloseRequest.

        token  # noqa: E501

        :param token: The token of this PostMarketCloseRequest.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def id(self):
        """Gets the id of this PostMarketCloseRequest.  # noqa: E501

        市场ID  # noqa: E501

        :return: The id of this PostMarketCloseRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PostMarketCloseRequest.

        市场ID  # noqa: E501

        :param id: The id of this PostMarketCloseRequest.  # noqa: E501
        :type: str
        """
        if id is not None and len(id) > 32:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `32`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def closing_reason(self):
        """Gets the closing_reason of this PostMarketCloseRequest.  # noqa: E501

        关闭原因  # noqa: E501

        :return: The closing_reason of this PostMarketCloseRequest.  # noqa: E501
        :rtype: str
        """
        return self._closing_reason

    @closing_reason.setter
    def closing_reason(self, closing_reason):
        """Sets the closing_reason of this PostMarketCloseRequest.

        关闭原因  # noqa: E501

        :param closing_reason: The closing_reason of this PostMarketCloseRequest.  # noqa: E501
        :type: str
        """
        if closing_reason is not None and len(closing_reason) > 400:
            raise ValueError("Invalid value for `closing_reason`, length must be less than or equal to `400`")  # noqa: E501
        if closing_reason is not None and len(closing_reason) < 1:
            raise ValueError("Invalid value for `closing_reason`, length must be greater than or equal to `1`")  # noqa: E501

        self._closing_reason = closing_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostMarketCloseRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostMarketCloseRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
