# coding: utf-8

"""
    kinmall 平台接口（保荐方平台端）

    `kinmall` 平台接口（保荐方平台端）  当前接口为 `sponsor` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@kinmall.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.sponsor
from swagger_client.sponsor.models.post_sendverification_code_request import PostSendverificationCodeRequest  # noqa: E501
from swagger_client.sponsor.rest import ApiException


class TestPostSendverificationCodeRequest:
    """PostSendverificationCodeRequest unit test stubs"""


    def testPostSendverificationCodeRequest(self):
        """Test PostSendverificationCodeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.post_sendverification_code_request.PostSendverificationCodeRequest()  # noqa: E501
        pass


