# coding: utf-8

"""
    kinmall 平台接口（保荐方平台端）

    `kinmall` 平台接口（保荐方平台端）  当前接口为 `sponsor` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@kinmall.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.sponsor
from swagger_client.sponsor.models.inline_response_200_1 import InlineResponse2001  # noqa: E501
from swagger_client.sponsor.rest import ApiException


class TestInlineResponse2001:
    """InlineResponse2001 unit test stubs"""


    def testInlineResponse2001(self):
        """Test InlineResponse2001"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_1.InlineResponse2001()  # noqa: E501
        pass


