# coding: utf-8

"""
    kinmall 平台接口（保荐方平台端）

    `kinmall` 平台接口（保荐方平台端）  当前接口为 `sponsor` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@kinmall.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.sponsor
from swagger_client.sponsor.models.put_sponsors_project_request import PutSponsorsProjectRequest  # noqa: E501
from swagger_client.sponsor.rest import ApiException


class TestPutSponsorsProjectRequest:
    """PutSponsorsProjectRequest unit test stubs"""


    def testPutSponsorsProjectRequest(self):
        """Test PutSponsorsProjectRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.put_sponsors_project_request.PutSponsorsProjectRequest()  # noqa: E501
        pass


