# coding: utf-8

"""
    otc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import pytest

import swagger_client.otc
from swagger_client.otc.models.query_balance_fow_resp import QueryBalanceFowResp  # noqa: E501
from swagger_client.otc.rest import ApiException


class TestQueryBalanceFowResp:
    """QueryBalanceFowResp unit test stubs"""


    def testQueryBalanceFowResp(self):
        """Test QueryBalanceFowResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_balance_fow_resp.QueryBalanceFowResp()  # noqa: E501
        pass


