# coding: utf-8

"""
    otc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.otc
from swagger_client.otc.models.get_assets_response import GetAssetsResponse  # noqa: E501
from swagger_client.otc.rest import ApiException


class TestGetAssetsResponse:
    """GetAssetsResponse unit test stubs"""


    def testGetAssetsResponse(self):
        """Test GetAssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_assets_response.GetAssetsResponse()  # noqa: E501
        pass


