# coding: utf-8

"""
    crush 平台接口（用户管理后台端）

    `crush` 平台接口（后台端）  当前接口为 `staff` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pytest
import json
import swagger_client.staff
from swagger_client.staff.api.venture_management_api import VentureManagementApi  # noqa: E501
from swagger_client.staff.rest import ApiException
from conftest import verify, login, logout, register, BACK_DOOR_VERIFY_CODE, rand_password, rand_email, rand_phone, rand_indiv_cert


api = swagger_client.staff.api.venture_management_api.VentureManagementApi()


def pytest_namespace():
    return {'email': "", "password": "", "base_token": "", "phone": ""}


class TestVentureManagementApi:
    """VentureManagementApi pytest stubs"""

    def test_register_and_login_prepare(self):
        country = "86"
        pytest.email = rand_email()
        pytest.password = rand_password()
        register(email=pytest.email, password=pytest.password, promotion_code="",
                 verification_code=BACK_DOOR_VERIFY_CODE,
                 country=country)

        pytest.base_token = login(api, pytest.email, pytest.password, challenge="", seccode=BACK_DOOR_VERIFY_CODE,
                                  validate="")
        print("register return base_token:%s" % pytest.base_token)

    def test_ventures_get(self):
        """Test case for ventures_get
        查询项目方用户列表  # noqa: E501
        """
        api.ventures_get(email='')

    def test_ventures_id_get(self):
        """Test case for ventures_id_get
        获取项目方用户信息  # noqa: E501
        """
        api.ventures_id_get(id='')

