# coding: utf-8

"""
    crush 平台接口（用户管理后台端）

    `crush` 平台接口（后台端）  当前接口为 `staff` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.staff
from swagger_client.staff.models.get_inviter_list_response_items import GetInviterListResponseItems  # noqa: E501
from swagger_client.staff.rest import ApiException


class TestGetInviterListResponseItems:
    """GetInviterListResponseItems unit test stubs"""


    def testGetInviterListResponseItems(self):
        """Test GetInviterListResponseItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_inviter_list_response_items.GetInviterListResponseItems()  # noqa: E501
        pass


