# coding: utf-8

"""
    crush 平台接口（用户管理后台端）

    `crush` 平台接口（后台端）  当前接口为 `staff` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.staff
from swagger_client.staff.models.get_tenant_list_response_tenant import GetTenantListResponseTenant  # noqa: E501
from swagger_client.staff.rest import ApiException


class TestGetTenantListResponseTenant:
    """GetTenantListResponseTenant unit test stubs"""


    def testGetTenantListResponseTenant(self):
        """Test GetTenantListResponseTenant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_tenant_list_response_tenant.GetTenantListResponseTenant()  # noqa: E501
        pass


