# coding: utf-8

"""
    crush 平台接口（用户管理后台端）

    `crush` 平台接口（后台端）  当前接口为 `staff` 端  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest
import json
import swagger_client.staff
from swagger_client.staff.api.sponsors_managerment_api import SponsorsManagermentApi  # noqa: E501
from swagger_client.staff.rest import ApiException
from conftest import verify, login, logout, register, BACK_DOOR_VERIFY_CODE, rand_password, rand_email, rand_phone, \
    rand_indiv_cert
from swagger_client.staff.models.put_sponsor_status_request import PutSponsorStatusRequest
from swagger_client.staff.models.post_sponsor_request import PostSponsorRequest
from swagger_client.staff.models.put_sponsor_request import PutSponsorRequest

api = swagger_client.staff.api.sponsors_managerment_api.SponsorsManagermentApi()


def pytest_namespace():
    return {'email': "", "password": "", "base_token": "", "phone": ""}


class TestSponsorsManagermentApi:
    """SponsorsManagermentApi pytest stubs"""

    def test_register_and_login_prepare(self):
        country = "86"
        pytest.email = rand_email()
        pytest.password = rand_password()
        register(email=pytest.email, password=pytest.password, promotion_code="",
                 verification_code=BACK_DOOR_VERIFY_CODE,
                 country=country)

        pytest.base_token = login(api, pytest.email, pytest.password, challenge="", seccode=BACK_DOOR_VERIFY_CODE,
                                  validate="")
        print("register return base_token:%s" % pytest.base_token)

    def test_staff_sponsor_status_put(self):
        """Test case for staff_sponsor_status_put
        修改保荐方状态  # noqa: E501
        """
        payload = {
            "id": "string",
            "status": "normal"
        }
        req = PutSponsorStatusRequest(**payload)
        api.staff_sponsor_status_put(put_sponsor_status=req)

    def test_staff_sponsors_get(self):
        """Test case for staff_sponsors_get
        管理后台获取保荐方列表  # noqa: E501
        """
        api.staff_sponsors_get(page=1)

    def test_staff_sponsors_post(self):
        """Test case for staff_sponsors_post
        新增保荐方信息  # noqa: E501
        """
        payload = {
            "account": "abc123",
            "name": "这是名称",
            "password": "string",
            "phone": "string",
            "email": "string"
        }
        req = PostSponsorRequest(**payload)
        api.staff_sponsors_post(post_sponsor=req)

    def test_staff_sponsors_put(self):
        """Test case for staff_sponsors_put
        修改保荐方信息  # noqa: E501
        """
        payload = {
            "id": "string",
            "logo": "url/images",
            "website": "www.baidu.com",
            "summary": "这是简介",
            "password": "string",
            "phone": "string",
            "email": "string"
        }
        req = PutSponsorRequest(**payload)
        api.staff_sponsors_put(put_sponsor=req)
