# coding: utf-8

"""
    crush-sponsor 平台接口（保荐方平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PutProjectSponsorRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'status': 'int',
        'remark': 'str'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'remark': 'remark'
    }

    def __init__(self, id=None, status=None, remark=None):  # noqa: E501
        """PutProjectSponsorRequest - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._status = None
        self._remark = None
        self.discriminator = None

        self.id = id
        self.status = status
        if remark is not None:
            self.remark = remark

    @property
    def id(self):
        """Gets the id of this PutProjectSponsorRequest.  # noqa: E501

        申请id  # noqa: E501

        :return: The id of this PutProjectSponsorRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PutProjectSponsorRequest.

        申请id  # noqa: E501

        :param id: The id of this PutProjectSponsorRequest.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def status(self):
        """Gets the status of this PutProjectSponsorRequest.  # noqa: E501

        1:接受，0:拒绝  # noqa: E501

        :return: The status of this PutProjectSponsorRequest.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PutProjectSponsorRequest.

        1:接受，0:拒绝  # noqa: E501

        :param status: The status of this PutProjectSponsorRequest.  # noqa: E501
        :type: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def remark(self):
        """Gets the remark of this PutProjectSponsorRequest.  # noqa: E501

        驳回原因  # noqa: E501

        :return: The remark of this PutProjectSponsorRequest.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this PutProjectSponsorRequest.

        驳回原因  # noqa: E501

        :param remark: The remark of this PutProjectSponsorRequest.  # noqa: E501
        :type: str
        """

        self._remark = remark

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutProjectSponsorRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutProjectSponsorRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
