# coding: utf-8

"""
    crush-otc 平台接口（法币交易）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetAssetsByCoinIdResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'balance': 'str',
        'frozen': 'str'
    }

    attribute_map = {
        'balance': 'balance',
        'frozen': 'frozen'
    }

    def __init__(self, balance=None, frozen=None):  # noqa: E501
        """GetAssetsByCoinIdResponse - a model defined in Swagger"""  # noqa: E501

        self._balance = None
        self._frozen = None
        self.discriminator = None

        if balance is not None:
            self.balance = balance
        if frozen is not None:
            self.frozen = frozen

    @property
    def balance(self):
        """Gets the balance of this GetAssetsByCoinIdResponse.  # noqa: E501

        可用金额  # noqa: E501

        :return: The balance of this GetAssetsByCoinIdResponse.  # noqa: E501
        :rtype: str
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """Sets the balance of this GetAssetsByCoinIdResponse.

        可用金额  # noqa: E501

        :param balance: The balance of this GetAssetsByCoinIdResponse.  # noqa: E501
        :type: str
        """

        self._balance = balance

    @property
    def frozen(self):
        """Gets the frozen of this GetAssetsByCoinIdResponse.  # noqa: E501

        冻结金额  # noqa: E501

        :return: The frozen of this GetAssetsByCoinIdResponse.  # noqa: E501
        :rtype: str
        """
        return self._frozen

    @frozen.setter
    def frozen(self, frozen):
        """Sets the frozen of this GetAssetsByCoinIdResponse.

        冻结金额  # noqa: E501

        :param frozen: The frozen of this GetAssetsByCoinIdResponse.  # noqa: E501
        :type: str
        """

        self._frozen = frozen

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetAssetsByCoinIdResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetAssetsByCoinIdResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
