# coding: utf-8

"""
    crush 平台接口（主平台）

    `crush` 平台接口（主平台）  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.main
from swagger_client.main.models.put_vps_request import PutVPSRequest  # noqa: E501
from swagger_client.main.rest import ApiException


class TestPutVPSRequest:
    """PutVPSRequest unit test stubs"""


    def testPutVPSRequest(self):
        """Test PutVPSRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.put_vps_request.PutVPSRequest()  # noqa: E501
        pass


