# coding: utf-8

"""
    crush 平台接口（主平台）

    `crush` 平台接口（主平台）  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.main
from swagger_client.main.models.get_entrusts_query import GetEntrustsQuery  # noqa: E501
from swagger_client.main.rest import ApiException


class TestGetEntrustsQuery:
    """GetEntrustsQuery unit test stubs"""


    def testGetEntrustsQuery(self):
        """Test GetEntrustsQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_entrusts_query.GetEntrustsQuery()  # noqa: E501
        pass


