# coding: utf-8

"""
    crush-tenant 平台接口(租户平台)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.tenant
from swagger_client.tenant.models.inline_response_200 import InlineResponse200  # noqa: E501
from swagger_client.tenant.rest import ApiException


class TestInlineResponse200:
    """InlineResponse200 unit test stubs"""


    def testInlineResponse200(self):
        """Test InlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.tenant.models.inline_response_200.InlineResponse200()  # noqa: E501
        pass


