# coding: utf-8

"""
    crush 租户平台接口

    `crush` 平台接口（后台端）  当前接口为 `tenant` 端，访问其它接口：`staff`, `venture`, `user`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: api@crush.team
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.tenant
from swagger_client.tenant.models.inline_response_401 import InlineResponse401  # noqa: E501
from swagger_client.tenant.rest import ApiException


class TestInlineResponse401:
    """InlineResponse401 unit test stubs"""


    def testInlineResponse401(self):
        """Test InlineResponse401"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_401.InlineResponse401()  # noqa: E501
        pass


