# coding: utf-8

"""
    crush-tenant 平台接口(租户平台)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.tenant
from swagger_client.tenant.models.get_withdrawable_lists_response_inner import GetWithdrawableListsResponseInner  # noqa: E501
from swagger_client.tenant.rest import ApiException


class TestGetWithdrawableListsResponseInner:
    """GetWithdrawableListsResponseInner unit test stubs"""


    def testGetWithdrawableListsResponseInner(self):
        """Test GetWithdrawableListsResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.tenant.models.get_withdrawable_lists_response_inner.GetWithdrawableListsResponseInner()  # noqa: E501
        pass


