# coding: utf-8

"""
    crush-tenant 平台接口(租户平台)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client.tenant
from swagger_client.tenant.models.post_close_phone_authenticator_request import PostClosePhoneAuthenticatorRequest  # noqa: E501
from swagger_client.tenant.rest import ApiException


class TestPostClosePhoneAuthenticatorRequest:
    """PostClosePhoneAuthenticatorRequest unit test stubs"""


    def testPostClosePhoneAuthenticatorRequest(self):
        """Test PostClosePhoneAuthenticatorRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.tenant.models.post_close_phone_authenticator_request.PostClosePhoneAuthenticatorRequest()  # noqa: E501
        pass


