# coding: utf-8

"""
    crush-tenant 平台接口(租户平台)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest
import json
from test.tenant.id_settings import *
from test.tenant.staff import Staff
from test.tenant.tenant import Tenant
from test.tenant.venture import Venture
from test.tenant.sponsor import Sponsor
from test.tenant.main import Main


@pytest.fixture(scope="function")
def setup(request):
    _staff = Staff(CONFIG.STAFF_INDEX)
    _tenant = Tenant(CONFIG.TENANT_INDEX)
    _venture = Venture(CONFIG.VENTURE_INDEX)
    _sponsor = Sponsor(CONFIG.SPONSOR_INDEX)
    _main = Main(CONFIG.MAIN_INDEX)

    def finalize():
        pass

    request.addfinalizer(finalize)
    return _staff, _main, _tenant, _venture, _sponsor


class TestQuotationApi:
    """QuotationApi pytest stubs"""

    def test_quotation_coins_id_get(self, setup):
        """Test case for quotation_coins_id_get
        单一币种在单一交易所所有币对的行情统计（24小时）（交易所成交量占比）  # noqa: E501
        """
        pass

    def test_quotation_historical_data_post(self, setup):
        """Test case for quotation_historical_data_post
        K线数据  # noqa: E501
        """
        pass

    def test_quotation_id_overview_get(self, setup):
        """Test case for quotation_id_overview_get
        单一币种在各交易所的行情概要  # noqa: E501
        """
        pass

