# coding: utf-8

"""
    crush-venture 平台接口（项目方平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetWithdrawAddressesResponseInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'coin_id': 'str',
        'address_tag': 'str',
        'remark': 'str',
        'address': 'str'
    }

    attribute_map = {
        'id': 'id',
        'coin_id': 'coinId',
        'address_tag': 'addressTag',
        'remark': 'remark',
        'address': 'address'
    }

    def __init__(self, id=None, coin_id=None, address_tag=None, remark=None, address=None):  # noqa: E501
        """GetWithdrawAddressesResponseInner - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._coin_id = None
        self._address_tag = None
        self._remark = None
        self._address = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if coin_id is not None:
            self.coin_id = coin_id
        if address_tag is not None:
            self.address_tag = address_tag
        if remark is not None:
            self.remark = remark
        if address is not None:
            self.address = address

    @property
    def id(self):
        """Gets the id of this GetWithdrawAddressesResponseInner.  # noqa: E501

        提币地址ID  # noqa: E501

        :return: The id of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetWithdrawAddressesResponseInner.

        提币地址ID  # noqa: E501

        :param id: The id of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def coin_id(self):
        """Gets the coin_id of this GetWithdrawAddressesResponseInner.  # noqa: E501

        币id  # noqa: E501

        :return: The coin_id of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._coin_id

    @coin_id.setter
    def coin_id(self, coin_id):
        """Sets the coin_id of this GetWithdrawAddressesResponseInner.

        币id  # noqa: E501

        :param coin_id: The coin_id of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :type: str
        """

        self._coin_id = coin_id

    @property
    def address_tag(self):
        """Gets the address_tag of this GetWithdrawAddressesResponseInner.  # noqa: E501

        地址标签  # noqa: E501

        :return: The address_tag of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._address_tag

    @address_tag.setter
    def address_tag(self, address_tag):
        """Sets the address_tag of this GetWithdrawAddressesResponseInner.

        地址标签  # noqa: E501

        :param address_tag: The address_tag of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :type: str
        """

        self._address_tag = address_tag

    @property
    def remark(self):
        """Gets the remark of this GetWithdrawAddressesResponseInner.  # noqa: E501

        地址备注  # noqa: E501

        :return: The remark of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this GetWithdrawAddressesResponseInner.

        地址备注  # noqa: E501

        :param remark: The remark of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def address(self):
        """Gets the address of this GetWithdrawAddressesResponseInner.  # noqa: E501

        提币地址  # noqa: E501

        :return: The address of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this GetWithdrawAddressesResponseInner.

        提币地址  # noqa: E501

        :param address: The address of this GetWithdrawAddressesResponseInner.  # noqa: E501
        :type: str
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetWithdrawAddressesResponseInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetWithdrawAddressesResponseInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
