# coding: utf-8

"""
    crush-venture 平台接口（项目方平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetVentureSponsorListResponseProjects(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'logo': 'str'
    }

    attribute_map = {
        'id': 'id',
        'logo': 'logo'
    }

    def __init__(self, id=None, logo=None):  # noqa: E501
        """GetVentureSponsorListResponseProjects - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._logo = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if logo is not None:
            self.logo = logo

    @property
    def id(self):
        """Gets the id of this GetVentureSponsorListResponseProjects.  # noqa: E501

        项目id  # noqa: E501

        :return: The id of this GetVentureSponsorListResponseProjects.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetVentureSponsorListResponseProjects.

        项目id  # noqa: E501

        :param id: The id of this GetVentureSponsorListResponseProjects.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def logo(self):
        """Gets the logo of this GetVentureSponsorListResponseProjects.  # noqa: E501

        项目logo  # noqa: E501

        :return: The logo of this GetVentureSponsorListResponseProjects.  # noqa: E501
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this GetVentureSponsorListResponseProjects.

        项目logo  # noqa: E501

        :param logo: The logo of this GetVentureSponsorListResponseProjects.  # noqa: E501
        :type: str
        """

        self._logo = logo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetVentureSponsorListResponseProjects, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetVentureSponsorListResponseProjects):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
