# coding: utf-8

"""
    crush-venture 平台接口（项目方平台）

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetProjectsResponseItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'str',
        'coin_id': 'str',
        'init': 'bool',
        'project_name': 'str',
        'full_name': 'str',
        'short_name': 'str',
        'coin_logo_key': 'str',
        'coin_logo_url': 'str',
        'latest_price': 'str',
        'chg_pct24_h': 'str',
        'amount24_h': 'str',
        'listed_exchange': 'str',
        'market_value': 'str',
        'invite': 'str'
    }

    attribute_map = {
        'project_id': 'projectId',
        'coin_id': 'coinId',
        'init': 'init',
        'project_name': 'projectName',
        'full_name': 'fullName',
        'short_name': 'shortName',
        'coin_logo_key': 'coinLogoKey',
        'coin_logo_url': 'coinLogoUrl',
        'latest_price': 'latestPrice',
        'chg_pct24_h': 'chgPct24H',
        'amount24_h': 'amount24H',
        'listed_exchange': 'listedExchange',
        'market_value': 'marketValue',
        'invite': 'invite'
    }

    def __init__(self, project_id=None, coin_id=None, init=None, project_name=None, full_name=None, short_name=None, coin_logo_key=None, coin_logo_url=None, latest_price=None, chg_pct24_h=None, amount24_h=None, listed_exchange=None, market_value=None, invite=None):  # noqa: E501
        """GetProjectsResponseItems - a model defined in Swagger"""  # noqa: E501

        self._project_id = None
        self._coin_id = None
        self._init = None
        self._project_name = None
        self._full_name = None
        self._short_name = None
        self._coin_logo_key = None
        self._coin_logo_url = None
        self._latest_price = None
        self._chg_pct24_h = None
        self._amount24_h = None
        self._listed_exchange = None
        self._market_value = None
        self._invite = None
        self.discriminator = None

        if project_id is not None:
            self.project_id = project_id
        if coin_id is not None:
            self.coin_id = coin_id
        if init is not None:
            self.init = init
        if project_name is not None:
            self.project_name = project_name
        if full_name is not None:
            self.full_name = full_name
        if short_name is not None:
            self.short_name = short_name
        if coin_logo_key is not None:
            self.coin_logo_key = coin_logo_key
        if coin_logo_url is not None:
            self.coin_logo_url = coin_logo_url
        if latest_price is not None:
            self.latest_price = latest_price
        if chg_pct24_h is not None:
            self.chg_pct24_h = chg_pct24_h
        if amount24_h is not None:
            self.amount24_h = amount24_h
        if listed_exchange is not None:
            self.listed_exchange = listed_exchange
        if market_value is not None:
            self.market_value = market_value
        if invite is not None:
            self.invite = invite

    @property
    def project_id(self):
        """Gets the project_id of this GetProjectsResponseItems.  # noqa: E501

        项目ID  # noqa: E501

        :return: The project_id of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this GetProjectsResponseItems.

        项目ID  # noqa: E501

        :param project_id: The project_id of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def coin_id(self):
        """Gets the coin_id of this GetProjectsResponseItems.  # noqa: E501

        币种ID  # noqa: E501

        :return: The coin_id of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._coin_id

    @coin_id.setter
    def coin_id(self, coin_id):
        """Sets the coin_id of this GetProjectsResponseItems.

        币种ID  # noqa: E501

        :param coin_id: The coin_id of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._coin_id = coin_id

    @property
    def init(self):
        """Gets the init of this GetProjectsResponseItems.  # noqa: E501

        是否初始化  # noqa: E501

        :return: The init of this GetProjectsResponseItems.  # noqa: E501
        :rtype: bool
        """
        return self._init

    @init.setter
    def init(self, init):
        """Sets the init of this GetProjectsResponseItems.

        是否初始化  # noqa: E501

        :param init: The init of this GetProjectsResponseItems.  # noqa: E501
        :type: bool
        """

        self._init = init

    @property
    def project_name(self):
        """Gets the project_name of this GetProjectsResponseItems.  # noqa: E501

        项目名称  # noqa: E501

        :return: The project_name of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this GetProjectsResponseItems.

        项目名称  # noqa: E501

        :param project_name: The project_name of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def full_name(self):
        """Gets the full_name of this GetProjectsResponseItems.  # noqa: E501

        币全称  # noqa: E501

        :return: The full_name of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this GetProjectsResponseItems.

        币全称  # noqa: E501

        :param full_name: The full_name of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def short_name(self):
        """Gets the short_name of this GetProjectsResponseItems.  # noqa: E501

        币种简称  # noqa: E501

        :return: The short_name of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this GetProjectsResponseItems.

        币种简称  # noqa: E501

        :param short_name: The short_name of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def coin_logo_key(self):
        """Gets the coin_logo_key of this GetProjectsResponseItems.  # noqa: E501

        币种图标KEY  # noqa: E501

        :return: The coin_logo_key of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._coin_logo_key

    @coin_logo_key.setter
    def coin_logo_key(self, coin_logo_key):
        """Sets the coin_logo_key of this GetProjectsResponseItems.

        币种图标KEY  # noqa: E501

        :param coin_logo_key: The coin_logo_key of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._coin_logo_key = coin_logo_key

    @property
    def coin_logo_url(self):
        """Gets the coin_logo_url of this GetProjectsResponseItems.  # noqa: E501

        币种图标URL  # noqa: E501

        :return: The coin_logo_url of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._coin_logo_url

    @coin_logo_url.setter
    def coin_logo_url(self, coin_logo_url):
        """Sets the coin_logo_url of this GetProjectsResponseItems.

        币种图标URL  # noqa: E501

        :param coin_logo_url: The coin_logo_url of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._coin_logo_url = coin_logo_url

    @property
    def latest_price(self):
        """Gets the latest_price of this GetProjectsResponseItems.  # noqa: E501

        最新成交价  # noqa: E501

        :return: The latest_price of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._latest_price

    @latest_price.setter
    def latest_price(self, latest_price):
        """Sets the latest_price of this GetProjectsResponseItems.

        最新成交价  # noqa: E501

        :param latest_price: The latest_price of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._latest_price = latest_price

    @property
    def chg_pct24_h(self):
        """Gets the chg_pct24_h of this GetProjectsResponseItems.  # noqa: E501

        24H涨跌幅  # noqa: E501

        :return: The chg_pct24_h of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._chg_pct24_h

    @chg_pct24_h.setter
    def chg_pct24_h(self, chg_pct24_h):
        """Sets the chg_pct24_h of this GetProjectsResponseItems.

        24H涨跌幅  # noqa: E501

        :param chg_pct24_h: The chg_pct24_h of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._chg_pct24_h = chg_pct24_h

    @property
    def amount24_h(self):
        """Gets the amount24_h of this GetProjectsResponseItems.  # noqa: E501

        24H成交量  # noqa: E501

        :return: The amount24_h of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._amount24_h

    @amount24_h.setter
    def amount24_h(self, amount24_h):
        """Sets the amount24_h of this GetProjectsResponseItems.

        24H成交量  # noqa: E501

        :param amount24_h: The amount24_h of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._amount24_h = amount24_h

    @property
    def listed_exchange(self):
        """Gets the listed_exchange of this GetProjectsResponseItems.  # noqa: E501

        已上交易所数量  # noqa: E501

        :return: The listed_exchange of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._listed_exchange

    @listed_exchange.setter
    def listed_exchange(self, listed_exchange):
        """Sets the listed_exchange of this GetProjectsResponseItems.

        已上交易所数量  # noqa: E501

        :param listed_exchange: The listed_exchange of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._listed_exchange = listed_exchange

    @property
    def market_value(self):
        """Gets the market_value of this GetProjectsResponseItems.  # noqa: E501

        市值  # noqa: E501

        :return: The market_value of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._market_value

    @market_value.setter
    def market_value(self, market_value):
        """Sets the market_value of this GetProjectsResponseItems.

        市值  # noqa: E501

        :param market_value: The market_value of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._market_value = market_value

    @property
    def invite(self):
        """Gets the invite of this GetProjectsResponseItems.  # noqa: E501

        邀请  # noqa: E501

        :return: The invite of this GetProjectsResponseItems.  # noqa: E501
        :rtype: str
        """
        return self._invite

    @invite.setter
    def invite(self, invite):
        """Sets the invite of this GetProjectsResponseItems.

        邀请  # noqa: E501

        :param invite: The invite of this GetProjectsResponseItems.  # noqa: E501
        :type: str
        """

        self._invite = invite

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetProjectsResponseItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetProjectsResponseItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
